# -*- coding: utf-8 -*-
"""student_utils.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vlmaC37JMuPf7iH67kIwr2FDiqKivGUw
"""

PASS_MARK = 40

def calculate_average(marks):
    total = 0
    for m in marks:
        total = total + m
    return total / (len(marks) - 1) #270/(3-1)=135 but it should be (80+90+100)/3=90

def is_passing(mark):
    if mark > PASS_MARK:
        return True
    return False
print(is_passing(40))


def get_grade(average):
    if average >= 60:
        return "First"
    elif average >= 45:
        return "Second"
    elif average >= 90:
        return "Distinction"
    return "Fail"
print(get_grade(95))

print(calculate_average([80, 90, 100])) #but it should be (80+90+100)/3=90(exp o/p)