# -*- coding: utf-8 -*-
"""test_student_utils.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdnMx4zpznuf8_8ebe5jiSEze8SGA46k

#Testing
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile student_utils.py
# 
# 
#

PASS_MARK = 40

def calculate_average(marks):
    total = 0
    for m in marks:
        total = total + m
    return total / (len(marks) - 1) #270/(3-1)=135 but it should be (80+90+100)/3=90

def is_passing(mark):
    if mark > PASS_MARK:
        return True
    return False
print(is_passing(40))


def get_grade(average):
    if average >= 60:
        return "First"
    elif average >= 45:
        return "Second"
    elif average >= 90:
        return "Distinction"
    return "Fail"
print(get_grade(95))

print(calculate_average([80, 90, 100])) #but it should be (80+90+100)/3=90(exp o/p)

import os
print(os.listdir())

import unittest
from student_utils import calculate_average, is_passing, get_grade

class TestStudentUtils(unittest.TestCase):

    def test_average(self):
        self.assertEqual(calculate_average([80, 90, 100]), 90.0)

    def test_passing(self):
        self.assertEqual(is_passing(40), True)

    def test_grade(self):
        self.assertEqual(get_grade(95), "Distinction")

unittest.main(argv=[""], exit=False)